### ISSUE TITLE
Incorrect LIB paths in NuGet package

### ISSUE THREAD

**Issue by JunielKatarn** [microsoft/hermes-windows#12]
See `__vcpkg.targets`:
```
      <AdditionalLibraryDirectories Condition="'$(__VcpkgNormalizedConfiguration)' == 'Release'">%(AdditionalLibraryDirectories);$(__VcpkgRoot)lib;$(__VcpkgRoot)lib\manual-link</AdditionalLibraryDirectories>
      <AdditionalLibraryDirectories Condition="'$(__VcpkgNormalizedConfiguration)' == 'Debug'">%(AdditionalLibraryDirectories);$(__VcpkgRoot)debug\lib;$(__VcpkgRoot)debug\lib\manual-link</AdditionalLibraryDirectories>
```

Library paths are suffixed with non-existing directory `manual-link`.
This prevents LIB dependencies from being resolved by consuming projects.

Suggested solution: Remove the `\manual-link` suffix from the `.targets` file.
Additional suggestion: Move MSBuild properties and item definitions into a `.props` file instead.

**Comment by tudorms** [comment]
Out of date, fixed a while ago with NuGet structure updates.
