### ISSUE TITLE
Calling toLocaleDateString on a Date object past year 3001 throws an unhandled exception

### ISSUE THREAD

**Issue by stecrain** [microsoft/hermes-windows#16]
## Bug Description

This looks like a bug in the Windows APIs being called by the C Runtime.

https://www.gizchina.com/2020/03/07/a-new-windows-10-bug-microsoft-has-980-years-to-fix-it/
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=vs-2019
 
_localtime64_s, which uses the __time64_t structure, allows dates to be expressed up through 23:59:59, January 18, 3001, coordinated universal time (UTC), whereas _localtime32_s represents dates through 23:59:59 January 18, 2038, UTC.

Hermes version: ReactNative.Hermes.Windows.0.1.6
React Native version (if any): 0.60
Android version (if any): n/a
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

## Steps To Reproduce

new Date("3002-10-06T03:59:59.0000000").toLocaleDateString()

## The Expected Behavior
No Crash :)

**Comment by Khalef1** [comment]
@stecrain - do you have a workaround for this or are you blocked? Checking to figure out the priority on fixing this.

**Comment by mganandraj** [comment]
Closing the outdated bug.

**Comment by mganandraj** [comment]
This issue was occurring on an initial version of Unicode stubs based on stl libraries. We later switched to icu based implementation.
