### ISSUE TITLE
__delayloadHelper2@8 missing from hermes.dll

### ISSUE THREAD

**Issue by asklar** [microsoft/hermes-windows#18]
I was playing with the Hermes DLL in a uwp app and I noticed that we set /delayload for it, but when I try to link against the Hermes dll from nuget I get an unresolved symbol for __delayloadHelper2@8
Any idea what might be going on? Or how RNW manages to avoid hitting this problem?

I’m using the nuget package ReactNative.Hermes 0.6.3 – 0245db04

**Comment by tudorms** [comment]
We need to add dloadhelper.lib to <AdditionalDependencies> in the .targets, since we're adding hermes.dll to DelayLoadDLLs.
