### ISSUE TITLE
PDBs don't match DLLs

### ISSUE THREAD

**Issue by asklar** [microsoft/hermes-windows#23]
The PDBs in the nuget package are mismatched with the binaries
using 0.6.3 nuget pkg

**Comment by tudorms** [comment]
Bug is here: https://github.com/microsoft/hermes-windows/blob/0245db0476c4fe13bbc165ebffb54fb049d09e58/cibuild.ps1#L137 The exe's PDB overwrites the library's.

**Comment by tudorms** [comment]
Fixed with https://github.com/microsoft/hermes-windows/pull/26
