### ISSUE TITLE
hermes.exe (bytecode generator) crashes on launch

### ISSUE THREAD

**Issue by asklar** [microsoft/hermes-windows#24]
0.6.3
![image](https://user-images.githubusercontent.com/22989529/95935657-9a472800-0d88-11eb-8ab9-3a161ec78662.png)

**Comment by NickGerleman** [comment]
I'm observing that the win32 flavor works correctly, but the UWP one does not. Maybe something is stubbed out that cannot be.

**Comment by tudorms** [comment]
Since the hermes bytecode is platform independent, we should probably just include a single compiler in the package (perhaps x86 or x64 win32/release). As a bonus we save on package size / disk space usage.

**Comment by tudorms** [comment]
Fixed with https://github.com/microsoft/hermes-windows/pull/26
