### ISSUE TITLE
jsi::String::utf8 does not preserve embedded NULs in Debug mode

### ISSUE THREAD

**Issue by dunhor** [microsoft/hermes-windows#88]
## Bug Description

NOTE: Originally from: https://github.com/microsoft/react-native-windows/issues/9681. The following descriptions are assuming use of RNW.

When building/running in debug mode, if a JavaScript function calls into a turbo module (that uses JSI) and passes a string that contains embedded NULs (e.g. `"foo\0bar"`), then the function in the native module - when it calls `jsi::String::utf8` to convert the string into a `std::string` - will only get the contents of the string up to the first embedded NUL character (e.g. `"foo"` in the earlier example). It seems that [this line](https://github.com/microsoft/hermes-windows/blob/fe145e9b46d68ba89d8be99def94b19a55caab82/API/hermes/hermes_dbg.h#L57) is to blame. It seems to make use of the [`IHermesString` interface](https://github.com/microsoft/hermes-windows/blob/fe145e9b46d68ba89d8be99def94b19a55caab82/API/hermes/hermes.h#L67) which only contains a `c_str` function. Therefore, the `std::string` constructor will only initialize the string up to the first NUL character.

The fix should be relatively simple: the `IHermesString` interface needs to also provide a `length`/`size` function, and then the `hermes_dbg.h` header needs to make use of this function.

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.10.0-ms.1
React Native version (if any): 0.67
OS version (if any): Windows Insider
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): amd64

## Steps To Reproduce

The easiest way to reproduce is to create a RNW application, set it to use Hermes, add a turbo module, introduce a function that expects a string, call it from JavaScript with a string that contains an embedded NUL, and then expect the contents of the string (e.g. in the debugger) after calling `jsi::String::utf8`.

## The Expected Behavior
Embedded NUL characters should be preserved in Debug like they are in Release

**Comment by asklar** [comment]
@mganandraj @tudorms FYI

**Comment by mganandraj** [comment]
@tudorms I believe you had fixed this one. Please close the bug if so.

**Comment by tudorms** [comment]
Yup, this should've been fixed a while back.
