### ISSUE TITLE
Hermes repeatable builds for NuGet packages

### ISSUE THREAD

**Issue by Khalef1** [microsoft/hermes-windows#91]
Port of https://github.com/microsoft/react-native-windows/issues/9772.

We don't currently keep good track of code that went into a certain Hermes NuGet release, e.g. there is a 0.9.0-ms branch, but that doesn't exactly match the code in the 0.9.0-ms.4 package (we get mismatched source warnings in the debugger).
This is because the branch seems to track only the latest for a given version.
It's important we address this for compliance / security reasons as well as debuggability.

The Hermes symbols seem to only available in symweb; they should be available in the public Microsoft symbol server.

**Comment by dannyvv** [comment]
Note: perhaps we should use the suffix i.e. `4` in `-ms.4` as the fourth value in the FileVersion.. As that is what debuggers tend to show, not the product version. So all 0.11.0-ms.n are currenlty the same version in the debugger...
