### ISSUE TITLE
Add MIT Licensing Information to nuget Package

### ISSUE THREAD

**Issue by dedavis6797** [microsoft/hermes-windows#98]
## Bug Description

Hermes currently does not include proper Licensing information which gets flagged by [component governance in ADO](https://microsoft.visualstudio.com/Universal%20Store/_componentGovernance/XS.SDX.Settings/alert/6855137?typeId=11792905). 

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.11.2

**Comment by jonthysell** [comment]
Adding license file to the package doesn't automatically register it as the package's license. Both the page on nuget.org (and Component Governance) still don't see that the package has an MIT license. See RNW's nuspec for an example of setting the right metadata.
